### PR TITLE
Fix the 'Unresolved Symbols' error caused by commit 21e692b

### PR DESCRIPTION
**Pull request by fantasydr**
1. The wke\wkeGlobalVar.cpp for global variables is not added into the VS2015 project files.  
2. The namespace is missing for g_isDecodeUrlRequest in WebURLLoaderManager.cpp file.

### CODE REVIEW

**Comment by weolar** [comment]
Thanks，I‘ll recommit again

**Comment by fantasydr** [comment]
OK. I'll just close this PR and wait for the updates.

**Comment by fantasydr** [comment]
There is a compilation error in 'Release' configuration.  I submitted a fix in my branch. https://github.com/fantasydr/miniblink49/commit/ebac8d4a0fda0bbc17c3e7331673457af41a590e

The lib is much faster in 'Release' mode and it works as expected. Thanks for providing the source code, it helps me lot 👍 

PS, since the owner prefer to recommit rather than merge, I didn't create new PR but only leave a comment instead.

**Comment by weolar** [comment]
Hi， I ‘m ’curious to know what is your product use?

**Comment by fantasydr** [comment]
I didn't use it in any product. I'm trying to understand how to reduce the size of chromium.
